apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: udp-config-coredns
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    k8s-app: kube-dns

---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: tcp-config-coredns
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    k8s-app: kube-dns
