apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: vitkazak/hipster-frontend:v0.0.1
    name: frontend
    env:
    - name: AD_SERVICE_ADDR
      value: "ad"
    - name: CART_SERVICE_ADDR
      value: "cart"
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkout"
    - name: CURRENCY_SERVICE_ADDR
      value: "currency"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "product-catalog"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendation"
    - name: SHIPPING_SERVICE_ADDR
      value: "shipping"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
