apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: docker.io/vitkazak/k8s-webserver
    volumeMounts:
    - name: app
      mountPath: /app
      readOnly: true
  initContainers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
      readOnly: false
  volumes:
  - name: app
    emptyDir: {}
